<?php

namespace Acme\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Types\Type;

/**
 * ChatMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatMessagesRepository extends EntityRepository
{
    /**
     * @param $startDate
     * @param $endDate
     * @return ChatMessages[]|null
     */
    public function getMessagesByTime($startDate, $endDate = null){

        /*->andWhere("cm.posted <= :endDate")*/
        /*->setParameter(":endDate", $endDate, Type::INTEGER)*/

        $query = $this->createQueryBuilder("cm")
            ->select("cm", "cu")
            ->join("cm.user", "cu")
            ->where("cm.posted >= :startDate")
            ->orderBy("cm.posted", "ASC")
            ->setParameter(":startDate", $startDate, Type::INTEGER)
            ->getQuery();

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
